name: Install Chromium
on:
  workflow_dispatch: # Allows manual triggering

jobs:
  install-chromium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          chromium-browser --version
      - name: Run Chromium
        run: |
         
          # URL to scrape
          URL="https://www.epam.com/careers/job-listings?country=Romania"

          # Run Chromium with virtual-time-budget to wait for rendering
          chromium-browser --headless=new --no-sandbox --disable-gpu --virtual-time-budget=10000 --dump-dom "$URL" --user-agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36" > output.html 2>/dev/null

           # Output the HTML to console
           cat output.html
