name: Install Chromium
on:
  workflow_dispatch: # Allows manual triggering

jobs:
  install-chromium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser
          chromium-browser --version
      - name: Run Chromium
        run: |
         chromium-browser --headless --no-sandbox --dump-dom https://www.epam.com/careers/job-listings?country=Romania
